### ISSUE TITLE
[DEV-52] docs(writebot): document array-type queries

### ISSUE THREAD

**Issue by samyosm** [samyosm/writebot#20]
<sub>From [SyncLinear.com](https://synclinear.com) | [DEV-52](https://linear.app/samyos/issue/DEV-52/docswritebot-document-array-type-queries)</sub>

**Comment by tushar1-000** [comment]
Hi how can I help you

**Comment by samyosm** [comment]
You can send an array of strings in the `makeQuery` method of a preset. As a result, Writebot will return multiple OpenAi responses. 

The code has been written but it hasn't been documented yet.

**Comment by tushar1-000** [comment]
I got an understanding of your projects so you want me to write the documentation. As I am new to open source you need to tell me more briefly. What should I have to do? So after  I can start working on it.

**Comment by samyosm** [comment]
This project uses Docusaurus for the documentation. Go the the appropriate files and write some doc.
